apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener-deployment
  labels:
    app: url-shortener
spec:
  replicas: 3 # Start with 3 instances of the app
  selector:
    matchLabels:
      app: url-shortener
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
      - name: url-shortener-app
        image: url-shortener-app:v2 # Use the image built earlier (or pushed)
        imagePullPolicy: Never # Use Minikube's local Docker image

        ports:
        - containerPort: 5000 # Port the Flask app listens on

        envFrom:
        - configMapRef:
            name: app-config # Reference the ConfigMap named 'app-config'

        # Resource requests (required for HPA to work)
        resources:
          requests:
            cpu: "100m"        # Request 0.1 CPU
            memory: "128Mi"    # Request 128 MiB memory
          # Optional: uncomment limits if desired
          # limits:
          #   cpu: "500m"
          #   memory: "256Mi"

        # Liveness and Readiness Probes
        readinessProbe:
          httpGet:
            path: /healthz
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /healthz
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20

